on:
    workflow_dispatch:
    workflow_call:

jobs:
  shared-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Connect to Artifactory
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: setup-frog-cli
      - name: Test OIDC
        run: |
          echo "Username: $(echo ${steps.setup-cli.outputs.oidc-user} | tr [a-z] [A-Z])"

      - name: Login to JFrog Artifactory docker registry
        uses: docker/login-action@v3
        with:
          registry: jfrog.oceaneering.com
          username: ${{ steps.setup-cli.outputs.oidc-user }}
          password: ${{ steps.setup-cli.outputs.oidc-token }}

      - name: Test pull
        run: docker pull jfrog.oceaneering.com/dockerhub-remote/redis:latest
