on:
  workflow_dispatch:
  workflow_call:

jobs:
  shared-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Test connection to Artifactory
        run: |
          curl -I https://secureartifactory.com/artifactory/api/system/ping

      - name: Print OIDC user and token
        run: |
          echo "OIDC User: ${{ steps.setup-cli.outputs.oidc-user }}"
          echo "OIDC Token: ${{ steps.setup-cli.outputs.oidc-token }}"

      - name: Connect to Artifactory
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://secureartifactory.com
          JF_PROJECT: setup-jfrog-cli
        with:
          oidc-provider-name: setup-jfrog-cli

      - name: Login to JFrog Artifactory docker registry
        uses: docker/login-action@v3
        with:
          registry: secureartifactory.com
          username: ${{ steps.setup-cli.outputs.oidc-user }}
          password: ${{ steps.setup-cli.outputs.oidc-token }}

      - name: Test pull
        run: docker pull secureartifactory.com/dockerhub-remote/redis:latest
