name: Debug OIDC Workflow

on:
  workflow_dispatch:
  workflow_call:

env:
  JF_URL: https://dockeroidctst.jfrogdev.org
  JF_PROJECT: setup-jfrog-cli

jobs:
  debug-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug OIDC Token
      run: |
        echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

    - name: Check Connectivity
      run: |
        curl -v ${{ env.JF_URL }}

    - name: Check Artifactory Version
      run: |
        curl -s ${{ env.JF_URL }}/artifactory/api/system/version

    - name: Manual OIDC Token Exchange
      run: |
        OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ env.JF_URL }}" | jq -r '.value')
        echo "OIDC Token obtained"
        RESPONSE=$(curl -H "Authorization: Bearer $OIDC_TOKEN" ${{ env.JF_URL }}/artifactory/api/security/token)
        echo "Response from Artifactory: $RESPONSE"

    - name: Setup JFrog CLI
      run: |
        curl -fL https://getcli.jfrog.io | sh
        ./jfrog config add artifactory --url=${{ env.JF_URL }} --interactive=false
        ./jfrog rt ping

    - name: Connect to Artifactory
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ env.JF_URL }}
        JF_PROJECT: ${{ env.JF_PROJECT }}
      with:
        oidc-provider-name: setup-jfrog-cli

    - name: Print OIDC user and token
      run: |
        echo "OIDC User: ${{ steps.setup-cli.outputs.oidc-user }}"
        echo "OIDC Token: ${{ steps.setup-cli.outputs.oidc-token }}"

    - name: Login to JFrog Artifactory docker registry
      uses: docker/login-action@v3
      with:
        registry: dockeroidctst.jfrogdev.org
        username: ${{ steps.setup-cli.outputs.oidc-user }}
        password: ${{ steps.setup-cli.outputs.oidc-token }}

    - name: Test pull
      run: docker pull dockeroidctst.jfrogdev.org/dockerhub-remote/redis:latest
