on:
  workflow_dispatch:
  workflow_call:

jobs:
  shared-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Connect to Artifactory
        id: setup-cli
        uses: jfrog/docker-ocid@main
        env:
          JF_URL: https://dockeroidca.jfrogdev.org
        with:
          oidc-provider-name: docker-ocid
      - name: Test OIDC
        run: |
          echo "Username: $(echo ${{ steps.setup-cli.outputs.oidc-user }} | tr [a-z] [A-Z])"

      - name: Login to JFrog Artifactory docker registry
        uses: docker/login-action@main
        with:
          registry: dockeroidca.jfrogdev.org
          username: ${{ steps.setup-cli.outputs.oidc-user }}
          password: ${{ steps.setup-cli.outputs.oidc-token }}

      - name: Test pull
        run: docker pull dockeroidca.jfrogdev.org/dockerocid/redis:latest
